FROM alpine:latest

RUN apk add --no-cache wget jq

RUN LATEST_VERSION=$(wget -qO- https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name | sed 's/v//') && \
    && wget https://github.com/fatedier/frp/releases/download/v${LATEST_VERSION}/frp_${LATEST_VERSION}_linux_amd64.tar.gz \
    && tar -xzf frp_${LATEST_VERSION}_linux_amd64.tar.gz \
    && mv frp_${LATEST_VERSION}_linux_amd64/frpc /usr/local/bin/ \
    && mkdir -p /etc/frp \
    && mv frp_${LATEST_VERSION}_linux_amd64/frpc.toml /etc/frp/frpc.toml \
    && rm -rf frp_${LATEST_VERSION}_linux_amd64 frp_${LATEST_VERSION}_linux_amd64.tar.gz

CMD ["frpc", "-c", "/etc/frp/frpc.toml"]
